[package]
name = "snake"
version = "0.1.0"
authors = ["Dominik Miedziński <dominik@mdzn.pl>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
fnv = "1.0.6"
piston_window = "0.105.0"
rand = "0.7.2"
rayon = "1.3.0"
